[2018-04-13 22:09:57,950] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 3 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-04-13 22:10:15,048] INFO [GroupMetadataManager brokerId=0] Removed 2 expired offsets in 2 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-04-13 22:10:15,054] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:10:15,056] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions  (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:10:15,056] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:10:15,068] INFO Log for partition mytest2-0 is renamed to /tmp/kafka-logs/mytest2-0.a9288eba9e6e4ac6aa0d350b098d5459-delete and is scheduled for deletion (kafka.log.LogManager)
[2018-04-13 22:10:15,145] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2018-04-13 22:10:15,145] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2018-04-13 22:10:15,147] INFO [KafkaApi-0] Auto creation of topic mytest2 with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
[2018-04-13 22:10:15,153] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup2 with old generation 3 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:10:15,153] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup with old generation 7 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:10:15,159] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:10:15,160] INFO [GroupCoordinator 0]: Stabilized group mygroup2 generation 4 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:10:15,160] INFO [GroupCoordinator 0]: Stabilized group mygroup generation 8 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:10:15,162] INFO Loading producer state from offset 0 for partition mytest2-0 with message format version 2 (kafka.log.Log)
[2018-04-13 22:10:15,163] INFO Completed load of log mytest2-0 with 1 log segments, log start offset 0 and log end offset 0 in 3 ms (kafka.log.Log)
[2018-04-13 22:10:15,164] INFO Created log for partition [mytest2,0] in /tmp/kafka-logs with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-04-13 22:10:15,165] INFO Replica loaded for partition mytest2-0 with initial high watermark 0 (kafka.cluster.Replica)
[2018-04-13 22:10:15,165] INFO [Partition mytest2-0 broker=0] mytest2-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2018-04-13 22:10:15,254] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup for generation 8 (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:10:15,254] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup2 for generation 4 (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:10:27,725] INFO Deleting index /tmp/kafka-logs/mytest2-0.a9288eba9e6e4ac6aa0d350b098d5459-delete/00000000000000000000.index (kafka.log.OffsetIndex)
[2018-04-13 22:10:27,742] INFO Deleting index /tmp/kafka-logs/mytest2-0.a9288eba9e6e4ac6aa0d350b098d5459-delete/00000000000000000000.timeindex (kafka.log.TimeIndex)
[2018-04-13 22:10:27,749] INFO Deleted log for partition mytest2-0 in /tmp/kafka-logs/mytest2-0.a9288eba9e6e4ac6aa0d350b098d5459-delete. (kafka.log.LogManager)
[2018-04-13 22:17:47,796] INFO [GroupMetadataManager brokerId=0] Removed 2 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-04-13 22:17:47,798] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:17:47,799] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions  (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:17:47,799] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:17:47,804] INFO Log for partition mytest2-0 is renamed to /tmp/kafka-logs/mytest2-0.82e986841a2847709c6d726ebeeb09f4-delete and is scheduled for deletion (kafka.log.LogManager)
[2018-04-13 22:17:47,852] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2018-04-13 22:17:47,852] INFO [KafkaApi-0] Auto creation of topic mytest2 with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
[2018-04-13 22:17:47,853] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2018-04-13 22:17:47,854] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup with old generation 8 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:17:47,854] INFO [GroupCoordinator 0]: Stabilized group mygroup generation 9 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:17:47,855] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup2 with old generation 4 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:17:47,855] INFO [GroupCoordinator 0]: Stabilized group mygroup2 generation 5 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:17:47,859] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:17:47,861] INFO Loading producer state from offset 0 for partition mytest2-0 with message format version 2 (kafka.log.Log)
[2018-04-13 22:17:47,861] INFO Completed load of log mytest2-0 with 1 log segments, log start offset 0 and log end offset 0 in 1 ms (kafka.log.Log)
[2018-04-13 22:17:47,862] INFO Created log for partition [mytest2,0] in /tmp/kafka-logs with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-04-13 22:17:47,862] INFO Replica loaded for partition mytest2-0 with initial high watermark 0 (kafka.cluster.Replica)
[2018-04-13 22:17:47,862] INFO [Partition mytest2-0 broker=0] mytest2-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2018-04-13 22:17:47,959] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup for generation 9 (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:17:47,959] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup2 for generation 5 (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:18:27,708] INFO Deleting index /tmp/kafka-logs/mytest2-0.82e986841a2847709c6d726ebeeb09f4-delete/00000000000000000000.index (kafka.log.OffsetIndex)
[2018-04-13 22:18:27,708] INFO Deleting index /tmp/kafka-logs/mytest2-0.82e986841a2847709c6d726ebeeb09f4-delete/00000000000000000000.timeindex (kafka.log.TimeIndex)
[2018-04-13 22:18:27,709] INFO Deleted log for partition mytest2-0 in /tmp/kafka-logs/mytest2-0.82e986841a2847709c6d726ebeeb09f4-delete. (kafka.log.LogManager)
[2018-04-13 22:19:57,933] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-04-13 22:29:30,729] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset-1} for Partition: mytest2-0. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-04-13 22:29:57,914] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-04-13 22:31:34,624] INFO [GroupMetadataManager brokerId=0] Removed 2 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-04-13 22:31:34,626] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:31:34,627] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions  (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:31:34,627] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:31:34,631] INFO Log for partition mytest2-0 is renamed to /tmp/kafka-logs/mytest2-0.35d9ad5d3b3641808b31bd1e4f170392-delete and is scheduled for deletion (kafka.log.LogManager)
[2018-04-13 22:31:34,827] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2018-04-13 22:31:34,828] INFO [KafkaApi-0] Auto creation of topic mytest2 with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
[2018-04-13 22:31:34,828] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2018-04-13 22:31:34,830] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup2 with old generation 5 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:31:34,830] INFO [GroupCoordinator 0]: Stabilized group mygroup2 generation 6 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:31:34,830] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup with old generation 9 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:31:34,831] INFO [GroupCoordinator 0]: Stabilized group mygroup generation 10 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:31:34,835] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:31:34,838] INFO Loading producer state from offset 0 for partition mytest2-0 with message format version 2 (kafka.log.Log)
[2018-04-13 22:31:34,838] INFO Completed load of log mytest2-0 with 1 log segments, log start offset 0 and log end offset 0 in 2 ms (kafka.log.Log)
[2018-04-13 22:31:34,839] INFO Created log for partition [mytest2,0] in /tmp/kafka-logs with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-04-13 22:31:34,839] INFO Replica loaded for partition mytest2-0 with initial high watermark 0 (kafka.cluster.Replica)
[2018-04-13 22:31:34,839] INFO [Partition mytest2-0 broker=0] mytest2-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2018-04-13 22:31:34,934] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup2 for generation 6 (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:31:34,934] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup for generation 10 (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:32:27,682] INFO Deleting index /tmp/kafka-logs/mytest2-0.35d9ad5d3b3641808b31bd1e4f170392-delete/00000000000000000000.index (kafka.log.OffsetIndex)
[2018-04-13 22:32:27,683] INFO Deleting index /tmp/kafka-logs/mytest2-0.35d9ad5d3b3641808b31bd1e4f170392-delete/00000000000000000000.timeindex (kafka.log.TimeIndex)
[2018-04-13 22:32:27,684] INFO Deleted log for partition mytest2-0 in /tmp/kafka-logs/mytest2-0.35d9ad5d3b3641808b31bd1e4f170392-delete. (kafka.log.LogManager)
[2018-04-13 22:36:03,143] INFO [GroupMetadataManager brokerId=0] Removed 2 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-04-13 22:36:03,146] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:36:03,146] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions  (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:36:03,147] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:36:03,150] INFO Log for partition mytest2-0 is renamed to /tmp/kafka-logs/mytest2-0.623efa96b59346899ebc7abdd87e734d-delete and is scheduled for deletion (kafka.log.LogManager)
[2018-04-13 22:36:03,259] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2018-04-13 22:36:03,260] INFO [KafkaApi-0] Auto creation of topic mytest2 with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
[2018-04-13 22:36:03,260] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2018-04-13 22:36:03,261] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup2 with old generation 6 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:36:03,262] INFO [GroupCoordinator 0]: Stabilized group mygroup2 generation 7 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:36:03,262] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup with old generation 10 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:36:03,262] INFO [GroupCoordinator 0]: Stabilized group mygroup generation 11 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:36:03,267] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions mytest2-0 (kafka.server.ReplicaFetcherManager)
[2018-04-13 22:36:03,268] INFO Loading producer state from offset 0 for partition mytest2-0 with message format version 2 (kafka.log.Log)
[2018-04-13 22:36:03,269] INFO Completed load of log mytest2-0 with 1 log segments, log start offset 0 and log end offset 0 in 1 ms (kafka.log.Log)
[2018-04-13 22:36:03,269] INFO Created log for partition [mytest2,0] in /tmp/kafka-logs with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-04-13 22:36:03,269] INFO Replica loaded for partition mytest2-0 with initial high watermark 0 (kafka.cluster.Replica)
[2018-04-13 22:36:03,270] INFO [Partition mytest2-0 broker=0] mytest2-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2018-04-13 22:36:03,366] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup for generation 11 (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:36:03,366] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup2 for generation 7 (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:36:27,676] INFO Deleting index /tmp/kafka-logs/mytest2-0.623efa96b59346899ebc7abdd87e734d-delete/00000000000000000000.index (kafka.log.OffsetIndex)
[2018-04-13 22:36:27,676] INFO Deleting index /tmp/kafka-logs/mytest2-0.623efa96b59346899ebc7abdd87e734d-delete/00000000000000000000.timeindex (kafka.log.TimeIndex)
[2018-04-13 22:36:27,677] INFO Deleted log for partition mytest2-0 in /tmp/kafka-logs/mytest2-0.623efa96b59346899ebc7abdd87e734d-delete. (kafka.log.LogManager)
[2018-04-13 22:36:28,295] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset-1} for Partition: mytest2-0. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-04-13 22:39:57,891] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-04-13 22:43:32,048] INFO Terminating process due to signal SIGHUP (kafka.Kafka$)
[2018-04-13 22:43:32,050] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2018-04-13 22:43:32,051] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2018-04-13 22:43:32,407] WARN Session 0x10000580ae7000d for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:32,509] INFO zookeeper state changed (Disconnected) (org.I0Itec.zkclient.ZkClient)
[2018-04-13 22:43:32,509] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2018-04-13 22:43:32,803] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:32,804] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:34,721] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup2 with old generation 7 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:43:34,722] INFO [GroupCoordinator 0]: Group mygroup2 with generation 8 is now empty (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:43:34,784] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:34,785] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:34,823] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup with old generation 11 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:43:34,823] INFO [GroupCoordinator 0]: Group mygroup with generation 12 is now empty (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2018-04-13 22:43:35,826] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:35,827] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:37,359] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:37,359] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:37,620] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:37,621] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:39,012] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:39,013] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:39,214] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:39,214] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:40,616] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:40,617] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:40,930] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:40,931] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:42,546] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:42,547] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:43,451] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:43,451] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:45,512] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:45,513] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:46,586] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:46,587] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:48,368] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:48,368] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:48,918] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:48,918] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:50,661] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:50,662] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:51,667] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:51,668] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:53,653] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:53,653] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:53,767] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:53,768] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:55,270] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:55,271] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:55,563] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:55,563] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:57,604] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:57,605] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:43:58,097] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:43:58,097] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:00,089] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:00,090] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:01,101] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:01,102] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:02,682] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:02,683] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:03,662] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:03,663] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:05,528] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:05,529] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:05,640] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:05,641] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:06,938] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:06,938] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:07,558] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:07,559] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:08,673] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:08,674] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:09,218] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:09,219] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:11,207] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:11,208] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:11,943] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:11,943] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:13,907] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:13,908] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:14,872] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:14,873] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:16,837] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:16,838] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:17,932] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:17,933] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:19,234] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:19,234] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:20,027] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:20,028] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:21,689] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:21,690] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:22,117] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:22,117] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:23,765] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:23,766] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:23,873] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:23,873] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:25,843] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:25,844] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:26,900] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:26,900] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-04-13 22:44:28,142] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-13 22:44:28,143] WARN Session 0x10000580ae7000d for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
